# datamario24/ruby314notejs:1.0.3-smashing-new-bundle
FROM ruby:3.1.4

RUN apt-get update && \
    apt-get upgrade -yq && \
    apt-get install -yq nodejs

RUN gem install smashing -v 1.3.6

RUN smashing new app

WORKDIR /app

RUN bundle
